2022-01-14 06:29:16,775:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-01.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:29:33,266:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-02.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:29:51,453:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-03.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:30:11,886:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-04.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:30:35,615:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-05.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:31:02,482:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-06.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:31:29,270:INFO:src.ETL:upload_raw_data_to_azure:yellow_tripdata_2021-07.csv was succesfully moved to raw-yellow-taxi-data
2022-01-14 06:31:29,343:INFO:src.ETL:upload_raw_data_to_azure:Raw data was successfully transfered and deleted from data/raw folder.
2022-01-14 06:35:32,804:INFO:src.ETL:extract_raw_taxi_data_from_azure:blob was successfuly extracted
2022-01-14 06:35:32,814:INFO:src.ETL:extract_raw_taxi_data_from_azure:ALL files were SUCCESSFULLY moved from blob storage -> machine
2022-01-14 06:37:46,822:INFO:src.ETL:transform_raw_data:All files were successfuly transformed and extracted raw data removed.
2022-01-14 06:37:47,029:ERROR:src.ETL:upload_transformed_data_to_azure:there is problem uploading transformed data to azure blob storage
Traceback (most recent call last):
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/src/ETL.py", line 241, in upload_transformed_data_to_azure
    self.blob_service_client.create_container(container_name)
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/storage/blob/_blob_service_client.py", line 518, in create_container
    container.create_container(
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/storage/blob/_container_client.py", line 299, in create_container
    process_storage_error(error)
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 177, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/storage/blob/_container_client.py", line 291, in create_container
    return self._client.container.create( # type: ignore
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 133, in create
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/mantas/PycharmProjects/makaw_assesment/makaw_assesment/.venv/lib/python3.9/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified container already exists.
RequestId:f4d43baa-801e-00ed-4d00-0955fb000000
Time:2022-01-14T04:37:46.9765677Z
ErrorCode:ContainerAlreadyExists
2022-01-14 06:37:55,806:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-01.csv
2022-01-14 06:38:04,475:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-02.csv
2022-01-14 06:38:16,734:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-03.csv
2022-01-14 06:38:33,269:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-04.csv
2022-01-14 06:38:49,695:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-05.csv
2022-01-14 06:39:07,945:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-06.csv
2022-01-14 06:39:43,697:INFO:src.ETL:extract_transformed_taxi_data_from_azure:blob exctarcted clean_yellow_trip_data_2021-07.csv
2022-01-14 06:39:43,699:INFO:src.ETL:extract_transformed_taxi_data_from_azure:ALL transformed taxi data files were SUCCESSFULLY moved from azure
